name: flutter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route: ^11.1.0 # Option 2 for routing
  connectivity_plus: ^7.0.0
  dio: ^5.9.1 # REST Networking 
  flutter_bloc: ^9.1.1 # State management
  flutter_cache_manager: ^3.4.1
  freezed_annotation: ^3.1.0 # Generated model mapping
  get_it: ^9.2.0 # Dependency injection in conjunction with injectable
  go_router: ^17.1.0 # Option 1 for routing - my preference
  hydrated_bloc: ^10.1.1 # Easy local caching
  injectable: ^2.7.1+4 # Dependency injection in conjunction with get_it
  intl: ^0.20.2
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  auto_route_generator: ^10.4.0 # Generates Typed routes if using auto_route
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0 # Generates Typed asset strings
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3 # Generated model mapping
  go_router_builder: ^4.2.0 # Generates Typed routes if using go_router
  injectable_generator: ^2.9.1   # Generates dynamic dependencies in conjunction with get_it
  json_serializable: ^6.11.2 # Generated model mapping
  mocktail: ^1.0.4 # Testing library
  very_good_analysis: ^10.0.0 # Code quality analysis in conjunction with analysis_options.yaml

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
